apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: orders-secrets
  namespace: orders
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: orders-secrets
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: aws-credentials
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: aws-credentials
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: DB_HOST
      remoteRef:
        key: production/rds/postgres-v4
        property: db_host
    - secretKey: DB_USERNAME
      remoteRef:
        key: production/rds/postgres-v4
        property: db_username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: production/rds/postgres-v4
        property: db_password
    - secretKey: DB_NAME
      remoteRef:
        key: production/rds/postgres-v4
        property: dbname
    - secretKey: DB_ENGINE
      remoteRef:
        key: production/rds/postgres-v4
        property: engine
    - secretKey: DB_PORT
      remoteRef:
        key: production/rds/postgres-v4
        property: port
