name: CI

on:
  push:
    branches: [ develop, main ]
    paths-ignore:
      - 'k8s/**'
  workflow_dispatch: {}

jobs:
  call-reusable-build-and-test-workflow:
    uses: railsonribeiro/nested-reusable-java-maven-eks-fork/.github/workflows/build.yml@main
    with:
      app_name: "pos-tech-g57-app-orders"
      dockerhub_username: "postechf57"
    secrets: inherit

  call-cd:
    needs: call-reusable-build-and-test-workflow
    if: ${{ github.ref == 'refs/heads/main' && needs.call-reusable-build-and-test-workflow.outputs.new_image_pushed == 'true' }}
    uses: ./.github/workflows/cd.yaml
    secrets: inherit
